version: "3.8"
services:
  image-service:
    image: image-service:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - s3
  s3:
    image: scireum/s3-ninja:6
    ports:
      - "9444:9000"